pin date-fns to 2.27.0 to unbreak build
Looks like date-fns at 2.28.0 has broken require('date-fns/format') style
imports, and so 'concurrently' fails to run with:

 % yarn start
yarn run v1.22.18
$ concurrently --kill-others-on-fail ...
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'date-fns/format'
Require stack:
- /Users/matthew/workspace/element-web/node_modules/concurrently/src/logger.js

Therefore, pin it to 2.27.0 for now.